# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b232f79aa2ad59d8fe22966f7d3c6a50c4e949b7dc33a2614f03f7026b925a02abd1d7fb2ec3e3536f9b3188480c7c81439e937f789357fbaab3fb8addfd9950

test:
  secret_key_base: 21514df1dad6657d9feb4525ca3b7b29bd21e1f47a4f37722ccac9903a0a7ac30c548847c1d330c9cd900d5fece178cec4dc41a6eeded9717b9f09ce29e05614

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
